Add description about status and types
aergoio/aips pull request #1
Opened 2019-08-29 08:17 UTC by kjunu

Please review English.

2019-08-29 08:26 UTC, graup commented on AIPS/aip-1.md
> +# AIP Status ( Work Flow )
```suggestion
# AIP Status (Work Flow)
```

2019-08-29 08:26 UTC, graup commented on AIPS/aip-1.md
> +# AIP Status ( Work Flow )
```suggestion
# AIP Status (Work Flow)
```

2019-08-29 08:30 UTC, graup requested changes

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +# AIP Status ( Work Flow )
```suggestion
# AIP Status (Work Flow)
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +Basically anyone can suggest their ideas to Aergo community.
```suggestion
Everyone can suggest their ideas to the Aergo community.
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> + 1. None
```suggestion
 1. Start
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +     * Aergo team will review the pull request and discuss on the GitHub.
```suggestion
     * Aergo team will review the pull request and discuss on GitHub.
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +     * If idea is accepted. Aergo Team start to develop.
```suggestion
     * If idea is accepted, Aergo Team starts to develop.
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +     * It will be applied on the mainnet by code.
```suggestion
     * After the code is released and tested, the mainnet will be upgraded.
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +There are n types of AIP:
```suggestion
There are 3 types of AIP:
```

2019-08-29 08:30 UTC, graup commented on AIPS/aip-1.md
> +     * Describes a blockchain parameters. for example, changing the number of block producers.
```suggestion
     * Describes a blockchain parameter. for example, changing the number of block producers.
```

2019-08-29 09:05 UTC, kjunu commented
@graup Thank you :)

2019-09-02 01:59 UTC, graup requested changes

2019-09-02 01:59 UTC, graup commented on AIPS/aip-1.md
> +     * Describes a blockchain parameter. for example, changing the number of block producers.
```suggestion
     * Describes the change of a blockchain parameter. For example, changing the number of block producers.
```

2019-09-02 01:59 UTC, graup commented on AIPS/aip-1.md
> +     * If idea is accepted, Aergo Team starts to develop.
```suggestion
     * If idea is accepted, Aergo team starts to develop.
```

2019-09-06 08:42 UTC, merged